### ISSUE TITLE
What is the header name to utilise limit_by header config?

### ISSUE THREAD

**Issue by pawandhiman10** [dream11/kong-scalable-rate-limiter#23]
Hello, could you help me with the header name to make use of limit_by: header.
I tried with different headers as below but seeing the same error again and again:
- http_x_forwarded_for
- client_ip
- remote_ip
- x_forwarded_for
- x-forwarded-for
- x-real-ip
- remote_addr

Error:
> 2024/03/27 19:26:18 [error] 10567#0: *6018 [kong] handler.lua:76 [scalable-rate-limiter] No rate-limiting identifier found in request, client: 110.225.87.235, server: kong, request: "POST /api HTTP/2", host: "example.com"

Also, when I try to get the KEYS in redis cluster, it is returning empty. The above mentioned headers work with the default rate-limiting plugin. Does it need headers with a new name in this plugin?

**Comment by justinDdoran** [comment]
You set the `header_name` in your limit_by config
https://github.com/dream11/kong-scalable-rate-limiter/blob/master/docs/index.md
